#!/usr/bin/env node
const compare = require('reviewers-edition-compare')
const fs = require('fs')
const glob = require('glob')
const path = require('path')
const { spawnSync } = require('child_process')
const spell = require('reviewers-edition-spell')

const partials = {}
glob.sync('partials/*.html').forEach(file => {
  const basename = path.basename(file, '.html')
  partials[basename] = fs.readFileSync(file, 'utf8')
})

const forms = {
  'confidentiality-ip': {
    title: 'Confidentiality and Intellectual Property Terms',
    description: 'covers protection of conditional information and ownership of rights in work done'
  },
  contractor: {
    title: 'Contractor Terms',
    description: 'legal terms for contracting'
  },
  employee: {
    title: 'Employee Terms',
    description: 'legal terms for employees'
  },
  'offer-letter': {
    title: 'Offer Letter Template',
    description: 'the document employers sign with new employees'
  },
  'statement-of-work': {
    title: 'Statement of Work Template',
    description: 'the document clients sign with new contractors'
  }
}

Object.keys(forms).forEach(subdirectory => {
  const { title, description } = forms[subdirectory]
  const editions = glob.sync(`${subdirectory}/*.rtf`)
    .map(file => path.basename(file, '.rtf'))
    .sort(compare)
    .reverse()
  const htmlFile = `${subdirectory}/index.html`
  fs.writeFileSync(htmlFile, `
<!doctype html>
<html lang=en-US>
<head>
${partials.meta}
  <title>${title}</title>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Square One">
  <meta name="twitter:description" content="${title}">
  <meta name="twitter:image" content="https://squareoneforms.com/logo-on-white-250.png">
  <meta property="og:description" content="${title}">
  <meta property="og:image" content="https://squareoneforms.com/logo-on-white-250.png">
  <meta property="og:site_name" content="Square One">
  <meta property="og:title" content="Square One">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://squareoneforms.com/">
</head>
<body>
${partials.header}
<main role=main>
  <h2>${title}</h2>
  <p>${description}</p>
  ${editions.map(code => `<h3 id=${code}>${capitalize(spell(code))}</h3>${fileLinks(subdirectory, code, title)}`).join('')}
</main>
${partials.footer}
</body>
</html>
  `.trim())
  spawnSync('tidy', ['-modify', '-config', './tidy.config', htmlFile])
})

function fileLinks (subdirectory, edition, title) {
  const forms = {
    html: { text: 'Read Online', download: false, stripExtension: true },
    rtf: { text: 'Download RTF', download: true },
    docx: { text: 'Download for Microsoft Word', download: true },
    pdf: { text: 'Download PDF', download: true }
  }
  let returned = ''
  Object.keys(forms).forEach(extension => {
    if (fs.existsSync(path.join(subdirectory, `${edition}.${extension}`))) {
      const download = `Square One ${title} ${edition}.${extension}`
      const info = forms[extension]
      const href = info.stripExtension
        ? `/${subdirectory}/${edition}`
        : `/${subdirectory}/${edition}.${extension}`
      returned += `<p><a${info.download ? ` download="${download}"` : ''} href=${href}>${info.text}</a></p>`
    }
  })
  returned += ''
  return returned
}

function capitalize (spelling) {
  return spelling
    .split(' ')
    .map(word => word[0].toUpperCase() + word.slice(1))
    .join(' ')
}
